language: php

branches:
    only:
    - master

matrix:
    fast_finish: true
    include:
    - php: 7.1
      env:
      - EXECUTE_CS_CHECK=false
      - EXECUTE_PHPSTAN=false

    - php: 7.2
      env:
      - EXECUTE_CS_CHECK=true
      - EXECUTE_PHPSTAN=true

cache:
    directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
- mkdir -p "$HOME/.php-cs-fixer"
- phpenv config-rm xdebug.ini
- composer install

script:
- if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer check-cs; fi
- if [[ EXECUTE_PHPSTAN == 'true' ]]; then composer phpstan; fi
- composer test
